version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - misspell
    - unconvert
    - ineffassign
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Wameedh/ccflow

output:
  formats:
    text:
      path: stdout
