version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - misspell
    - unconvert
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Wameedh/ccflow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
  max-issues-per-linter: 50
  max-same-issues: 10
